### ISSUE TITLE
CAFClassic - Invalid Index

### ISSUE THREAD

**Issue by Lachlan-White** [aztfmod/terraform-azurerm-caf-naming#2]
### Description
Attempting to name a storage account with the `type` of `st` causes an error of `invalid index`
This happens for the other `types` also.

Believe this issue is because within the `module.tf` file there is no logic for the `cafclassic` convention:
```
resource "random_string" "fullrandom" {
  count = (var.convention == "random" || var.convention == "cafrandom" )  == true ? 1 : 0
  length  = local.max
  special = false
  lower   = true
  upper   = false
}
```

### Error Message
```
Error: Invalid index

  on terraform-azurerm-caf-naming/module.tf line 25, in locals:
  25:   random                = random_string.fullrandom[0].result
    |----------------
    | random_string.fullrandom is empty tuple

The given key does not identify an element in this collection value.
```
### Code Example
```
variable "name" {
  type    = string
  default = "test"
}

variable "convention" {
  default = "cafclassic"
}

module "caf_name_st" {
  source = "./terraform-azurerm-caf-naming"

  name       = var.name
  type       = "st"
  convention = var.convention
}

output "st_value" {
  value = module.caf_name_st.st
}
```
### Expected Behaviour
Able to use the cafclassic naming convention for the supported `types`

### Actual
Error on all `cafclassic` `types` fue to invalid index

**Comment by arnaudlh** [comment]
Issue is happening due to: 

- resource "random_string" "fullrandom" {

  count = (var.convention == "random" || var.convention == "cafrandom" )  == true ? 1 : 0

- random                = random_string.fullrandom[0].result

So when we use passthrough or cafclassic version, we don't generate the local "random" which creates the invalid index error. 

Will disable the count on random string for the time being.
